### ISSUE TITLE
Implement `update` for keystore config.

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-kms-http#32]
This was a [TODO](https://github.com/digitalbazaar/bedrock-kms-http/commit/7a48af64d483d47d3b0fda47f819260fafdf39df#diff-1c0f1c434b17b7f8795d44a51a14320aR134)

**Comment by mattcollier** [comment]
There is an existing `/recovery` route here: https://github.com/digitalbazaar/bedrock-kms-http/blob/bd8a455a65c1b881357936033a0d32952d44d4e9/lib/http.js#L114-L166

- This route should be repurposed to generically update keystore configs.
- The route should require zcap authorization using the `authorizeZcapInvocation` middleware here: https://github.com/digitalbazaar/ezcap-express/blob/initial/lib/authorize.js#L33
- Any session base auth on this route should be removed.

There are two use cases for updating a keystore config
1. Profile bootstrapping
   1. During profile creating in the front end, there is a `capabilityAgent` that is the `controller` of the keystore.  The controller needs to be changed to be the `profile`.  The `updateKeystoreController` API is used for this purpose: https://github.com/digitalbazaar/bedrock-profile/blob/master/lib/kms.js#L45
   2. The `capabilityAgent` should have a root zcap to invoke in order to change the controller on the keystore.
1. Key recovery
   1. A wallet application has a root zcap for creating/updating keystores.
   2. Wallet would invoke its root zcap to update the controller on the keystore.

**Comment by dlongley** [comment]
This will be addressed by #54.
